name: Project_Cypress_Cucumber 
on: [push]
jobs: 
  cypress-run:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v4.1.4
      - name: Cypress.io
        uses: cypress-io/github-action@v6.5.0
        with: 
          start: npm test
      
